(defun Leaf/new (given-name f)
  (let ((name (format nil "~a/Leaf" given-name)))
    (let ((eh (Eh/new name)))
      `((handle . ,(lambda (msg) (funcall f msg)))
	(enter . ,(lambda ()))
	(exit . ,(lambda ()))
	(reset . ,(lambda ()))
	(step . ,(lambda () nil))
	(busy? . ,(lambda () nil))
	(%else . ,eh)
	))))
