(defun Leaf/new (f eh)
  `((handle . ,(lambda (msg) (funcall f msg)))
    (enter . ,(lambda ()))
    (exit . ,(lambda ()))
    (reset . ,(lambda ()))
    (step . ,(lambda () nil))
    (busy? . ,(lambda () nil))
    (%else . ,eh)
    ))
