(defun fixup (self)
(format *error-output* "fixup ~a~%" self)
  (cond ((null self) nil)
        ((eq '$Me self) self)
        ((not (listp self)) self)
        (t (cons (fixup (car self)) (fixup (cdr self))))))
