(defclass Runnable ()
  ((parent :accessor parent :initarg :parent)
   (name :accessor name :initarg :name)
   (top :accessor top :initarg :top)))

(defmethod run ((self Runnable))
  (loop while (busy-p self)
	do (step self))
  (loop while (handle-if-ready self)
	do (loop while (busy-p self)
		 do (step self))))
